### ISSUE TITLE
TODO List for Stage 1

### ISSUE THREAD

**Issue by MingjiHan99** [risinglightdb/risinglight#12]
Parser:
- [x] Parsing arithmetic expressions (`+`, `-`, `*` and `/`) @wangrunji0408 

- [x] Use `sqlparser` as new parser @wangrunji0408 

Binder: 
- [x] Add return names and types for select statement. @MingjiHan99 
- [x] Binding arithmetic expressions (`+`, `-`, `*` and `/`) @MingjiHan99  @wangrunji0408 
- [x] Add necessary implicit casting when binding the expressions. For example: ` 1.0 + 1` -> ` 1.0 + (1 cast as double)` @wangrunji0408 

Executor:
- [x] Implement expression evaluator and `ProjectionExecutor`. 
@MingjiHan99 @wangrunji0408 
- [x] Implement `CreateTableExecutor`,  and `InsertExecutor` @MingjiHan99 
@wangrunji0408 

Storage:
Implement on-disk storage system:

- [x] Add base definitions for table storage (`Segment` and `Block`)  @MingjiHan99 
- [x] Add disk manager @MingjiHan99 
- [ ] Add buffer pool （Ongoing）
