### ISSUE TITLE
feat: support TPC-H Q3

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#227]
TODO for supporting TPC-H Q3
- [x] Fix varchar to varchar casting #228 
- [x] Support decimal type #235 
- [x] Support date type
- [x] Case-insensitive column/table name
- [x] Support `order by` on expr alias #258 
- [x] Add testcase
- [x] Support implicit type casting (#280)
- [x] Support date comparison
- [x] Modify sqllogictest to support multi-line query in TPC-H
- [x] Support aggr with alias (#303)
- [ ] Support binop on decimal
- [ ] Generate input ref for group key
- [ ] Support typed string
- [ ] Load TPC-H data from risingwave
