### ISSUE TITLE
[Roadmap] RisingLight v0.1

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#317]
We plan to release RisingLight and RisingLight tutorial in late February.

## RisingLight Tutorial

RisingLight Tutorial is a step-by-step tutorial to build a RisingLight-like OLAP database. It will be in Chinese. We plan to release 3 parts:

* Intro (Basic framework of a database)
* <del>Query (How to run a query on a database)</del>
* Storage (A merge-tree-based column storage)

## RisingLight

RisingLight is an OLAP educational database. We plan to implement new features and fix bugs before RisingLight's release.

### Able to execute TPC-H 1, 3, 6 with optimal plans

Tracking issue:
- https://github.com/singularity-data/risinglight/issues/227
- https://github.com/singularity-data/risinglight/issues/325

* Support related executors
  - [x] TopN https://github.com/risinglightdb/risinglight/issues/404
  - [x] FilterScan
  - [x] HashJoin
* Optimizer
  - [x] Rust-flavor visitor framework
  - [x] Join-related rules
* Data types
  - [x] Decimal
  - [x] Date
* Better user interface
  - [x] Add column name for query results https://github.com/risinglightdb/risinglight/issues/231
  - [x] INSERT INTO ... SELECT ... https://github.com/risinglightdb/risinglight/issues/102

### Able to store and query <del>~20GB</del> ~10GB of data in storage

- [x] Support RLE encoding for efficient data representation https://github.com/risinglightdb/risinglight/issues/255
- [x] Support filter scan in storage layer https://github.com/risinglightdb/risinglight/issues/189
- [x] #348

### Docs

- [ ] Design docs about optimizer, storage, ...

**Comment by skyzh** [comment]
Some updates on RisingLight Tutorial -- we have finished about 50% of code and 20% of tutorial docs. It's still in a private repo, and will be made public later this month (if possible).

**Comment by MingjiHan99** [comment]
`INSERT INTO ... SELECT ...`
I could have a try.

**Comment by evanxg852000** [comment]
@skyzh Please what's the status of the tutorial docs? 
Been waiting on this as I would like to start working through them.

**Comment by skyzh** [comment]
> @skyzh Please what's the status of the tutorial docs? 
> 
> Been waiting on this as I would like to start working through them.

It is delayed to next month :)
