### ISSUE TITLE
TODO List for stage 2

### ISSUE THREAD

**Issue by MingjiHan99** [risinglightdb/risinglight#33]
- [x] Support aggregation function: Implement `GlobalAggregationOperator` and `HashAggregationOperator` @pleiadesian 
  - [x] https://github.com/singularity-data/risinglight/issues/55
  - [x] https://github.com/singularity-data/risinglight/issues/54
- [x] Support `where`, `order by`, `limit` and `offset`
  - #38 
  - #71 
  - #75 
- [x] #49
  - #41 
  - #44 
- [x] https://github.com/singularity-data/risinglight/issues/40
- [x] https://github.com/singularity-data/risinglight/issues/48
- [ ] Add optimizer framework and implement constant folding and predicate pushdown
