### ISSUE TITLE
Roadmap v0.2

### ISSUE THREAD

**Issue by skyzh** [risinglightdb/risinglight#572]
In v0.2, we focus on sorting everything -- from the composite sort key and primary key indexing in storage layer, to sort merge executors in executor layer, to composite key support in catalog.

## Storage

- [x] https://github.com/risinglightdb/risinglight/issues/588
- [x] https://github.com/risinglightdb/risinglight/issues/589
- [ ] refactor storage to support snapshot isolation
- [ ] refactor VersionManager to include catalog

## Optimizer

- [x] filter push-down optimizer rule for all operators
- [x] #654 
- [ ] add property to plan nodes https://github.com/risinglightdb/risinglight/issues/601

## Executor

- [x] optimize NestedLoopJoin to pull fewer data in memory https://github.com/risinglightdb/risinglight/issues/592
- [x] https://github.com/risinglightdb/risinglight/issues/591
- [x] https://github.com/risinglightdb/risinglight/issues/597
- [ ] new expression framework to vectorize any scalar function and support type inference

## SQL

- [x] support subquery in binder https://github.com/risinglightdb/risinglight/issues/578
- [x] add function call support https://github.com/risinglightdb/risinglight/pull/581
- [x] make catalog consistent https://github.com/risinglightdb/risinglight/issues/590

## Tutorial

- [ ] basic query engine (expected April)
- [ ] query execution
- [ ] storage

## Test Framework

- [x] https://github.com/risinglightdb/risinglight/issues/593

We're still drafting detailed design for each item, stay tuned! If you are interested in any of the item, please ping us in community channel for instructions, or create a tracking issue for that, thanks!

**Comment by MingjiHan99** [comment]
I will work on the binder for subquery.  
It is time to rewrite it :)

**Comment by skyzh** [comment]
> I will work on the binder for subquery.
> It is time to update it for subqueries :)

I've created a new issue for you :) By the way, you may ping @xxchan, who is recently working on subqueries support on RisingWave.

**Comment by evanxg852000** [comment]
The reason I started following this repo was because of the prosed learning via the tutorial. This roadmap feels more like the focus is shifting to building a production-grade DB. I think if the tutorial section is taken as a priority this will end up with more contributors (including me). Has been expecting the tutorials since February :disappointed:

**Comment by evanxg852000** [comment]
Thanks @xxchan, I think I will just forget about the tutorials and start picking some tasks. The reason I am so inclined about the tuts is that I would expect design docs or at least an architecture of the whole thing. I think this will make life easier before proper tutorial land. Like, have a document describing all the current components at high level.

**Comment by evanxg852000** [comment]
@xxchan thanks, I will make the jump this coming weekend. most likely asking too many questions while working on a real task will put more pressure on @skyzh to make the doc ready :smile: 
I can already sense how responsive the community is here.

**Comment by evanxg852000** [comment]
@wangrunji0408 No need to be sorry open source work is hard and thanks for giving more details. What I definitely would suggest is that do not wait until all is clean. we can read and give feedback as you write. You can be assured we will participate in helping (feedback and translation). Thanks for the hard work.

**Comment by lokax** [comment]
I want to support column pruning for some operators.
Can I have a try 😇 😇

**Comment by skyzh** [comment]
> I want to support column pruning for some operators.
> Can I have a try 😇 😇

Of course! Just create a tracking issue on which operator you're working on, thanks!

**Comment by sfsf9797** [comment]
Hi, love this project!! May I know if there is any timeline for the tutorials mentioned in the roadmap? Thanks

**Comment by skyzh** [comment]
Hopefully by the end of this year.

**Comment by skyzh** [comment]
See risinglight-tutorial in this org.
