### ISSUE TITLE
Tracking: next-gen planner & optimizer

### ISSUE THREAD

**Issue by wangrunji0408** [risinglightdb/risinglight#703]
We are going to rewrite the whole planner and optimizer using [egg](https://egraphs-good.github.io), a powerful crate to build [cascades-style](https://zhuanlan.zhihu.com/p/73545345) optimizers in Rust.

The new optimizer will be significantly small (expected 1k lines), more readable and maintainable than the current one.

### Roadmap

- [x] #702
- [x] fork the current binder, convert the sqlparser AST into the new egg AST.
   - [x] #705
   - [x] #707
   - [x] #717
- [x] #722 
- [x] #723 
- [x] construct executors from the egg AST.
  - [x] #725
  - [x] #726
  - [x] #727
  - [x] #728
- [ ] remove the old binder, planner and optimizer
  - [ ] #729
