### ISSUE TITLE
Tracking: support ClickBench

### ISSUE THREAD

**Issue by wangrunji0408** [risinglightdb/risinglight#765]
## Background

<img width="337" alt="chat" src="https://user-images.githubusercontent.com/15158738/211467373-83fbb9fc-bc0f-4ca9-bb20-c295624e17cb.png">

> We're looking for someone who can help RisingLight dominate the leaderboard. :)

https://github.com/ClickHouse/ClickBench

Welcome to contribute!

## Tasks

- [ ] Support SMALLINT type. (WIP)
- [ ] Support TIMESTAMP type.
- [ ] ... To be found
