### ISSUE TITLE
TODO list for stage 3

### ISSUE THREAD

**Issue by MingjiHan99** [risinglightdb/risinglight#86]
- [ ] Tutorial (from scratch + fill code)
- [ ] Storage Engine 
  #90 
- [ ] Optimizer 
  #111 
  #133
  #137
  #138
  #142
  #149
- [ ] Aggregation (group by)
- [ ] Data type (char varchar timestamp)
- [ ] Join algorithm
- [ ] TPC-H
  #112
  #154
  #97 
  #102
